[package]
name = "local"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bincode = "1.3.3"
env_logger = "0.11.5"
log = {version = "0.4.22", features = ["release_max_level_off"]}
serde = { version = "1.0.214", features = ["derive"] }
